name: Waka Readme
on:
  schedule:
    - cron: '0 17 * * *'  # Runs daily at 5:00 PM UTC (12:00 AM Cambodia time, UTC+7)
  workflow_dispatch:
jobs:
  update-readme:
    name: Auto Update Readme with Metrics
    runs-on: ubuntu-latest
    steps:
      - uses: anmol098/waka-readme-stats@master
        with:
          WAKATIME_API_KEY: ${{ secrets.WAKATIME_API_KEY }}
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          SHOW_PROFILE_VIEWS: "False"
          SHOW_OS: "False"
          SHOW_PROJECTS: "False"
          SHOW_EDITORS: "False"
          SHOW_LOC_CHART: "False"
          SHOW_LANGUAGE: "True"
          SHOW_LINES_OF_CODE: "True"
